# Source Code: https://github.com/marketplace/actions/is-website-vulnerable
name: Test site for publicly known js vulnerabilities

on:
  workflow_dispatch:
  push:
    branches:
      - test2
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Test for public javascript library vulnerabilities
        uses: lirantal/is-website-vulnerable@main
        with:
          scan-url: "https://confs.tech"
